### ISSUE TITLE
Missing download value

### ISSUE THREAD

**Issue by edouard-lopez** [beeryardtech/tmux-net-speed#1]
I went and executed the `download_speed.sh` script manually and I got this error:

```
~/.tmux/plugins/tmux-net-speed/scripts/helpers.sh: line 98: let: val+=: syntax error: operand expected (error token is "+=")
~/.tmux/plugins/tmux-net-speed/scripts/helpers.sh: line 98: let: val+=: syntax error: operand expected (error token is "+=")
0 B/s⏎
```

The [line is question is in `helpers.sh`](https://github.com/beeryardtech/tmux-net-speed/blob/6d0d551cef3cd38c51a7ec2fe32e851abfdc1d76/scripts/helpers.sh#L98).

**Comment by edouard-lopez** [comment]
It's break when the speed can't be detected. So a first step would be to use a default value as follow:

```
speed="$(echo -n $line | cut -d' ' -f $column)"
let val+=${speed:=0}
```

**Comment by edouard-lopez** [comment]
After more investigation I realize the output is wrong as you don't use my network interface (e.g. `wlp4s0`) but only `wlan0` and `eth0`:

```
++ for intf in '${interfaces[@]}'
+++ cut -d: -f 2
+++ grep eth0
+++ cat /proc/net/dev
++ line=
+++ cut '-d ' -f 1
+++ echo -n
++ speed=
++ let val+=0
++ for intf in '${interfaces[@]}'
+++ cat /proc/net/dev
+++ cut -d: -f 2
+++ grep wlan0
++ line=
+++ cut '-d ' -f 1
+++ echo -n
++ speed=
++ let val+=0
```

## Solution

You can get the [list of interfaces using kernel list](http://unix.stackexchange.com/a/125401/17362) in `/sys/class/net`:

```
declare -a interfaces=()
for interface in /sys/class/net/*; do 
    interfaces+=("$(basename $interface)"); 
done
```

### Sample

I got many interfaces due to `docker` containers:

```
$ echo ${interfaces[@]}
br-a49026d1a341 br-d26f2005f732 dm-5ab827835462 docker0 dummy0 enp0s25 lo veth2233650 veth62cdef1 veth6f4ae48 vethf6e81f8 wlp4s0
```

**Comment by Hettomei** [comment]
Hi,

same problem here, my 'wlan0' is named `wlp58s0` (ubuntu 16.04)
